services:
  api:
    build: .
    container_name: cm-pos-api
    command: npm run dev
    ports:
      - "4000:4000"
    env_file:
      - .env.example
    depends_on:
      - postgres
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  worker:
    build: .
    container_name: cm-pos-worker
    command: npm run worker
    env_file:
      - .env.example
    depends_on:
      - api
      - redis
      - postgres
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    container_name: cm-pos-postgres
    environment:
      POSTGRES_USER: pos_admin
      POSTGRES_PASSWORD: pos_password
      POSTGRES_DB: caisse_manager_showcase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: cm-pos-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: cm-pos-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  mongo_data:
  redis_data:
